"""CLI templates and constants — extracted from main.py for maintainability."""

# Fine-tuning specific config template — no BSP sections
FT_DEFAULT_CONFIG = """# PromptLab Configuration (Fine-Tuning Mode)
# Generated by: promptlab init --mode ft
# API keys are loaded from .env file via ${{VAR}} expansion — never hardcode secrets here.
version: 1

# =============================================================================
# FINE-TUNING GOVERNANCE
# =============================================================================
ft:
  config_file: ft_config.json
  governance_dir: .promptlab/governance
  # Auto-save council decisions to governance log
  log_decisions: true
  # Require chairman approval before applying config
  require_approval: false

# =============================================================================
# MODELS
# =============================================================================
models:
  default: {default_model}
  generator: {generator_model}
  
  providers:
{providers_block}

# =============================================================================
# LLM COUNCIL (used for hyperparameter governance)
# =============================================================================
council:
  enabled: {council_enabled}
  mode: fast  # full | fast | vote
  members:
{council_members}
  chairman: {council_chairman}
  # Minimum successful judge scores required (default: 2, min: 2)
  required_judges: 2
  # Strict mode: only use configured members, no fallback to pool
  use_fixed_judges: false
  # Show raw judge responses for debugging
  debug_judge_responses: false

# =============================================================================
# GIT INTEGRATION
# =============================================================================
git:
  enabled: true
  branch: null
  commit_template: "chore: FT governance council approved config (loss: {{loss:.4f}})"
  auto_push: false

# =============================================================================
# TESTING
# =============================================================================
testing:
  parallelism: 5
  timeout_ms: 180000
  retries: 2
"""

# Combined BSP + FT config template
BOTH_DEFAULT_CONFIG = """# PromptLab Configuration (BSP + Fine-Tuning)
# Generated by: promptlab init --mode both
# API keys are loaded from .env file via ${{VAR}} expansion — never hardcode secrets here.
version: 1

# =============================================================================
# BEHAVIOR SPECIFICATION PROMPT (BSP)
# =============================================================================
bsp:
  # Load BSP from file (recommended for version control)
  prompt_file: bsp.txt
  
  # Or use inline BSP:
  # prompt: |
  #   You are a helpful assistant.
  
  min_score: 0.7
  version: "1.0.0"
  auto_generate: true
  auto_generate_count: 50
  # generation_mode: "web" (scraping only) or "hybrid" (scraping + synthetic variants)
  generation_mode: web

# =============================================================================
# FINE-TUNING GOVERNANCE
# =============================================================================
ft:
  config_file: ft_config.json
  governance_dir: .promptlab/governance
  # Auto-save council decisions to governance log
  log_decisions: true
  # Require chairman approval before applying config
  require_approval: false

# =============================================================================
# MODELS
# =============================================================================
models:
  default: {default_model}
  generator: {generator_model}
  
  providers:
{providers_block}

# =============================================================================
# LLM COUNCIL
# =============================================================================
council:
  enabled: {council_enabled}
  mode: fast  # full | fast | vote
  members:
{council_members}
  chairman: {council_chairman}
  # Minimum successful judge scores required (default: 2, min: 2)
  required_judges: 2
  # Strict mode: only use configured members, no fallback to pool
  use_fixed_judges: false
  # Show raw judge responses for debugging
  debug_judge_responses: false

# =============================================================================
# BASELINE
# =============================================================================
baseline:
  storage_dir: .promptlab/baselines
  auto_update: true
  min_improvement: 0.01

# =============================================================================
# GIT INTEGRATION
# =============================================================================
git:
  enabled: true
  branch: null
  commit_template: "chore: PromptLab validation passed (score: {{score:.2f}}, improvement: +{{improvement:.2f}})"
  auto_push: false

# =============================================================================
# TESTING
# =============================================================================
testing:
  parallelism: 5
  timeout_ms: 180000
  retries: 2

# =============================================================================
# WEB SCRAPER (for auto-generating BSP test cases)
# =============================================================================
scraper:
  serpapi_key: ${{SERPAPI_KEY}}
  max_pages: 10
  timeout: 30
"""

# Default config template — comprehensive with all sections
DEFAULT_CONFIG = """# PromptLab Configuration
# Generated by: promptlab init
# API keys are loaded from .env file via ${{VAR}} expansion — never hardcode secrets here.
version: 1

# =============================================================================
# BEHAVIOR SPECIFICATION PROMPT (BSP)
# =============================================================================
bsp:
  # Load BSP from file (recommended for version control)
  prompt_file: bsp.txt
  
  # Or use inline BSP:
  # prompt: |
  #   You are a helpful assistant.
  
  min_score: 0.7
  version: "1.0.0"
  auto_generate: true
  auto_generate_count: 50
  # generation_mode: "web" (scraping only) or "hybrid" (scraping + synthetic variants)
  generation_mode: web

# =============================================================================
# MODELS
# =============================================================================
models:
  default: {default_model}
  generator: {generator_model}
  
  providers:
{providers_block}

# =============================================================================
# LLM COUNCIL
# =============================================================================
council:
  enabled: {council_enabled}
  mode: fast  # full | fast | vote
  members:
{council_members}
  chairman: {council_chairman}
  # Minimum successful judge scores required (default: 2, min: 2)
  required_judges: 2
  # Strict mode: only use configured members, no fallback to pool
  use_fixed_judges: false
  # Show raw judge responses for debugging
  debug_judge_responses: false

# =============================================================================
# BASELINE
# =============================================================================
baseline:
  storage_dir: .promptlab/baselines
  auto_update: true
  min_improvement: 0.01

# =============================================================================
# GIT INTEGRATION
# =============================================================================
git:
  enabled: true
  branch: null
  commit_template: "chore: BSP validation passed (score: {{score:.2f}}, improvement: +{{improvement:.2f}})"
  auto_push: false

# =============================================================================
# TESTING
# =============================================================================
testing:
  parallelism: 5
  timeout_ms: 180000
  retries: 2

# =============================================================================
# WEB SCRAPER (for auto-generating test cases)
# =============================================================================
scraper:
  serpapi_key: ${{SERPAPI_KEY}}
  max_pages: 10
  timeout: 30
"""


# Provider config blocks for template — all use ${VAR} env references
PROVIDER_BLOCKS = {
    "ollama": """    ollama:
      endpoint: http://localhost:11434""",
    "openrouter": """    openrouter:
      api_key: ${OPENROUTER_API_KEY}""",
    "google": """    google:
      api_key: ${GOOGLE_API_KEY}""",
    "openai": """    openai:
      api_key: ${OPENAI_API_KEY}""",
    "anthropic": """    anthropic:
      api_key: ${ANTHROPIC_API_KEY}""",
    "xai": """    xai:
      api_key: ${XAI_API_KEY}""",
        "nvidia": """    nvidia:
            api_key: ${NVIDIA_API_KEY}""",
}

# Default models per provider
DEFAULT_MODELS = {
    "ollama": "ollama/llama3.1:8b",
    "openrouter": "openrouter/google/gemini-2.0-flash-001",
    "google": "google/gemini-2.5-flash",
    "openai": "openai/gpt-4o-mini",
    "anthropic": "anthropic/claude-3-haiku-20240307",
    "xai": "xai/grok-2",
    "nvidia": "nvidia/deepseek-ai/deepseek-v3.2",
}

# Council configs per provider
COUNCIL_CONFIGS = {
    "ollama": {
        "members": ["ollama/llama3.1:8b", "ollama/mistral:7b"],
        "chairman": "ollama/llama3.1:8b",
    },
    "openrouter": {
        "members": ["openrouter/meta-llama/llama-3.3-70b-instruct:free", "openrouter/google/gemma-3-27b-it:free"],
        "chairman": "openrouter/arcee-ai/trinity-large-preview:free",
    },
    "google": {
        "members": ["google/gemini-2.5-flash", "google/gemini-2.0-flash-lite"],
        "chairman": "google/gemini-2.5-pro",
    },
    "openai": {
        "members": ["openai/gpt-4o-mini", "openai/gpt-3.5-turbo"],
        "chairman": "openai/gpt-4o",
    },
    "anthropic": {
        "members": ["anthropic/claude-3-haiku-20240307"],
        "chairman": "anthropic/claude-3-5-sonnet-20241022",
    },
    "xai": {
        "members": ["xai/grok-2"],
        "chairman": "xai/grok-2",
    },
    "nvidia": {
        "members": ["nvidia/deepseek-ai/deepseek-v3.2", "nvidia/deepseek-ai/deepseek-v3.1"],
        "chairman": "nvidia/deepseek-ai/deepseek-v3.2",
    },
}

# Example test template
EXAMPLE_TEST = """# Example test suite
metadata:
  name: Example Tests
  
defaults:
  model: ollama/llama3.1:8b
  temperature: 0

cases:
  - id: hello-world
    prompt: "Say hello in one word."
    assertions:
      - type: contains
        value: hello
        case_sensitive: false
        
  - id: math-simple
    prompt: "What is 2 + 2? Answer with just the number."
    assertions:
      - type: contains
        value: "4"
"""

# BSP template file
BSP_TEMPLATE = """# Behavior Specification Prompt (BSP)
# ============================================================================
# This file defines how your AI assistant should behave.
# PromptLab uses this to test and validate your prompts.
# ============================================================================

# CORE IDENTITY
# -------------
You are a helpful, accurate, and concise assistant.

# BEHAVIORAL GUIDELINES
# --------------------
1. Always provide factual, well-researched information
2. If you're uncertain about something, acknowledge it clearly
3. Keep responses brief and focused unless more detail is requested
4. Use clear, professional language
5. Structure complex answers with headings or bullet points

# CONSTRAINTS
# ----------
- Never fabricate information or citations
- Don't make promises about capabilities you don't have
- Avoid repetitive phrases and filler content
- Don't start responses with "I" when possible

# OUTPUT FORMAT
# -------------
- For simple questions: 1-2 sentence answers
- For explanations: structured paragraphs with clear flow
- For lists: use bullet points or numbered items
- For code: use markdown code blocks with language tags

# TONE
# ----
Professional yet approachable. Helpful without being verbose.
"""

# Root .gitignore template
GITIGNORE_TEMPLATE = """# PromptLab
.promptlab/
promptlab_cache/

# Environment secrets — NEVER commit this
.env

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
env/
.venv/

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
logs/
"""

GITHUB_WORKFLOW = '''# PromptLab CI/CD Workflow
name: Prompt Validation

on:
  pull_request:
    paths: ['prompts/**', 'temp/**', 'promptlab.yaml', 'bsp/**']
  push:
    branches: [main]
    paths: ['prompts/**', 'temp/**', 'promptlab.yaml', 'bsp/**']

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install PromptLab
        run: pip install promptlab
      
      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.ai/install.sh | sh
          ollama serve &
          sleep 5
          ollama pull llama3.1:8b
          ollama pull mistral:7b
      
      - name: Run BSP Validation
        run: promptlab validate --ci --output validation-result.json
      
      - name: Upload Validation Results
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: |
            validation-result.json
            .promptlab/runs/
      
      - name: Auto-Push on Improvement (optional)
        if: success() && github.ref == 'refs/heads/main'
        run: |
          # Uncomment to enable auto-push when score improves
          # git config user.name github-actions
          # git config user.email github-actions@github.com
          # promptlab validate --push --ci
          echo "BSP Validation passed! Enable auto-push in workflow to automatically update baselines."
'''


FT_CONFIG_TEMPLATE = """{
  "tuning_goal": "Minimize eval loss while maintaining generalization",
  "task_domain": "general",
  "base_model": "unsloth/Qwen2.5-1.5B",
  "judge_models": [
    "google/gemini-2.5-flash",
    "google/gemini-2.0-flash-lite",
    "openrouter/meta-llama/llama-3.3-70b-instruct:free"
  ],
  "chairman_model": "google/gemini-2.5-pro",
  "search_space": {
    "learning_rate": {"min": 1e-6, "max": 5e-4},
    "lora_rank": {"min": 4, "max": 64, "step": 4},
    "lora_alpha": {"min": 8, "max": 128, "step": 8},
    "num_epochs": {"min": 1, "max": 10},
    "warmup_ratio": {"min": 0.0, "max": 0.2},
    "weight_decay": {"min": 0.0, "max": 0.1},
    "scheduler_types": ["cosine", "linear", "constant_with_warmup"],
    "batch_sizes": [2, 4, 8, 16],
    "gradient_accumulation_steps": [1, 2, 4, 8]
  },
  "hardware_profile": {
    "gpu_type": "T4",
    "gpu_count": 1,
    "vram_gb": 16.0,
    "max_training_hours": 4.0
  },
  "dataset_profile": {
    "name": "my_dataset",
    "num_samples": 1000,
    "avg_input_length": 256,
    "avg_output_length": 128,
    "task_types": ["instruction_following"]
  }
}
"""
